prep-css-flexbox - Matthew Kweon
MattKweon/prep-0622-code-solutions pull request #9
Opened 2022-06-10 04:21 UTC by MattKweon

![Screen Shot 2022-06-09 at 9 16 45 PM (2)](https://user-images.githubusercontent.com/105886708/172989736-7e938dbd-2c91-4e5f-b6e1-c1ef3c3cd144.png)
![Screen Shot 2022-06-09 at 9 17 10 PM (2)](https://user-images.githubusercontent.com/105886708/172989749-fd892d14-8a5b-46a5-9d5f-366389d7972c.png)
![Screen Shot 2022-06-09 at 9 17 13 PM (2)](https://user-images.githubusercontent.com/105886708/172989756-05c8436b-4871-46eb-a474-ae098c495eac.png)
![Screen Shot 2022-06-09 at 9 17 15 PM (2)](https://user-images.githubusercontent.com/105886708/172989769-6dfab847-32e4-4a2c-86ab-d2ed0bdcf51b.png)

2022-06-10 21:39 UTC, thebearingedge requested changes

2022-06-10 21:39 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +      flex-basis: 25%;
Hi Matt, in each of your HTML files, try moving the `flex-basis` property to the rule set selecting the `.card-wrapper`.

`flex-basis` is meant to be applied to the children of a flex container.

2022-06-11 01:12 UTC, MattKweon commented
![Screen Shot 2022-06-10 at 6 10 37 PM](https://user-images.githubusercontent.com/105886708/173166923-704082a0-b956-4127-ab79-50d216924159.png)
![Screen Shot 2022-06-10 at 6 10 59 PM](https://user-images.githubusercontent.com/105886708/173166928-1b4afeb1-71ba-48ff-93e4-9c305879c0c1.png)
![Screen Shot 2022-06-10 at 6 11 18 PM](https://user-images.githubusercontent.com/105886708/173166930-42175521-c6c2-400c-b5b3-57a149951a90.png)
![Screen Shot 2022-06-10 at 6 11 40 PM](https://user-images.githubusercontent.com/105886708/173166931-be2a1ecc-df0d-49b9-9c52-e415f1801c9f.png)

2022-06-11 15:30 UTC, thebearingedge approved these changes

2022-06-11 17:05 UTC, merged